привел все к единому целому
yukis-data/team-project-group19 pull request #20
Opened 2022-02-20 19:49 UTC by Pavel-Kubrakov

2022-02-20 20:49 UTC, Andrii-Rodchenko reviewed
Тут конфликтов много вылезло, лучше сам посмотри

2022-02-21 15:17 UTC, yukis-data requested changes

2022-02-21 15:17 UTC, yukis-data commented on src/index.html
>      <include src="./partials/header.html"></include>
два хедера, это первый

2022-02-21 15:17 UTC, yukis-data commented on src/index.html
>      <include scr="./partials/header.html"></include>
вот второй

2022-02-21 15:17 UTC, yukis-data commented on src/sass/components/_hero.scss
> +.hero {
лайк, падписка, колокольчик, но кинь исправленный вариант Александру и Мише, они делают героя, я не понимаю какого героя мне заливать 
а так ты 🔥

2022-02-21 15:17 UTC, yukis-data commented on src/sass/main.scss
> +@import 'components/_footer';
нижнее подчеркивание не нужно

2022-02-21 15:54 UTC, yukis-data commented on src/sass/main.scss
> +@import 'components/_footer';
это фикс

2022-02-21 16:20 UTC, yukis-data commented on src/sass/main.scss
> +@import 'components/_footer';
внимательно проверяй, ибо удалил _variables.scss из импорта, где цвета

2022-02-21 20:22 UTC, merged