add hero section
yukis-data/team-project-group19 pull request #8
Opened 2022-02-19 17:45 UTC by allx-under

add hero section without imgs

2022-02-19 21:47 UTC, Pavel-Kubrakov requested changes

2022-02-19 21:47 UTC, Pavel-Kubrakov commented on src/sass/components/_hero.scss
> +    & span {
дай span отдельный класс. если кто то еще будет его узать, может все поломаться

2022-02-19 21:47 UTC, Pavel-Kubrakov commented on src/sass/components/_hero.scss
> +@media screen and (max-width:767px){
сначала классы а в них медиа запрос

2022-02-20 12:43 UTC, Pavel-Kubrakov requested changes

2022-02-20 12:43 UTC, Pavel-Kubrakov commented on src/sass/components/_hero.scss
> +    & span {
не изменил

2022-02-20 12:43 UTC, Pavel-Kubrakov commented on src/sass/components/_hero.scss
> +@media screen and (max-width:767px){
тоже

2022-02-20 18:05 UTC, allx-under commented on src/sass/components/_hero.scss
> +    & span {
fixed

2022-02-20 18:06 UTC, allx-under commented on src/sass/components/_hero.scss
> +@media screen and (max-width:767px){
fixed

2022-02-20 20:25 UTC, Pavel-Kubrakov approved these changes

2022-02-20 20:25 UTC, merged